version: '3'
services:
  api-soshop:
    build:
      context: .
      dockerfile: build/api/Dockerfile
    image: api-soshop
    container_name: api-soshop
    volumes:
      - "./api-soshop/:/var/www/html/api-soshop"
  api-mariadb:
    image: mariadb:10.1.12
    container_name: api-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=userApi
      - MYSQL_PASSWORD=mdpApi
      - MYSQL_DATABASE=api