version: '3'
services:
  api-soshop:
    build:
      context: .
      dockerfile: build/api-soshop/Dockerfile
    ports:
      - "8888:80"
    networks:
      - back-network
  api-mariadb:
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/:/var/lib/mysql"
    networks:
      - back-network
networks:
  back-network:
    driver: bridge