version: '3'
services:
  app-sf:
    build:
      context: .
      dockerfile: build/api/Dockerfile
    image: api
    container_name: api
    volumes:
      - "./api/:/var/www/html/api"
  mariadb-api:
    image: mariadb:10.1.12
    container_name: mariadb-api
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=userApi
      - MYSQL_PASSWORD=mdpApi
      - MYSQL_DATABASE=api