version: '3'
services:
  app-sf:
    build:
      context: .
      dockerfile: build/api/Dockerfile
    ports:
      - "8888:80"
    networks:
      - back-network
  mariadb-api:
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/:/var/lib/mysql"
    networks:
      - back-network
networks:
  back-network:
    driver: bridge